version: '3.9'
services:
    mongo:
    image: mongo:latest
    environment:
       - MONGO_INITDB_DATABASE=Connections 
       - MONGO_INITDB_ROOT_USERNAME=root
       - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    ports: 
    - 27017:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
  messagebus:
    image: rabbitmq:latest
  logging:
    build: ./loggingAPI
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
    volumes:
      - ./data:/data
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - messagebus
  web:
    build: ./Server
    ports:
      - 3000:3000
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - messagebus
  secondweb:
    build: ./secondserver
    ports:
      - 3001:3001
    links:
      - mongo
    environment:
      - MESSAGE_QUEUE=amqp://messagebus
      - DB_USERNAME=root
      - DB_PASSWORD=rootPassXXX
      - HOSTNAME=mongo
      - DB_PORT=27017
      - DB_NAME=Test
      - DB_PARAMS=?authSource=admin
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - messagebus
      - mongo